env:
    browser: true
    es2021: true
    jest: true
    node: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
    - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
    - react-hooks
    - '@typescript-eslint'
    - prettier
rules:
    # React specific
    react/react-in-jsx-scope: 'off'
    # WARNINGS
    camelcase: warn
    comma-dangle: warn
    quotes:
        - warn
        - single
    max-len:
        - warn
        - 100
    # ERRORS
    no-duplicate-imports: error
    # OFF
    '@typescript-eslint/no-empty-interface': 'off'
settings:
    import/resolver:
        typescript: {}
